version: "3.8"

services:
  minecraft-papa:
    image: itzg/minecraft-server:java11
    tty: true
    stdin_open: true
    ports:
      - "25565:25565" # default MC TCP port
      - "19565:19565" # prometheus logging exporter
    environment:
      - MAX_MEMORY: "4G"
      - MEMORY: "2G"
      - EULA: "TRUE"
      - VERSION: "1.16.5"
      - MODE: "survival"
      - TYPE: "FORGE"
      - SERVER_NAME: "Pixelmon en una papa"
      - MOTD: "Pixelmon on a Potato"
      - OP=${MINECRAFT_OP}
      - MODS: "https://dl.reforged.gg/4dvlYEb,https://mediafilez.forgecdn.net/files/3802/698/ftb-ranks-forge-1605.1.6-build.33.jar,https://mediafilez.forgecdn.net/files/3553/840/ftb-library-forge-1605.3.4-build.90.jar,https://mediafilez.forgecdn.net/files/4521/290/architectury-1.32.68.jar"
    volumes:
      - /root/applications/minecraft/data:/data:Z
      - /root/applications/minecraft/config:/config:Z
    restart: on-failure:3
    networks:
      minecraft:
        aliases:
          - minecraft-papa
